variable "name" {}
variable "project" {}
variable "region" {}
variable "network" {}
variable "ip_range" {}
variable "pod_subnet" {}
variable "svc1_subnet" {}
variable "svc2_subnet" {}
variable "svc3_subnet" {}
variable "svc4_subnet" {}
variable "somevar" {}
